/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as HabitosRouteImport } from './routes/habitos'
import { Route as HojeRouteImport } from './routes/hoje'
import { Route as MesRouteImport } from './routes/mes'
import { Route as ObjetivosRouteImport } from './routes/objetivos'
import { Route as MaisIndexRouteImport } from './routes/mais.index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as ProjetosProjectIdRouteImport } from './routes/projetos.$projectId'
import { Route as ApiHealthDebugRouteImport } from './routes/api.health.debug'
import { Route as ApiHealthRecentRouteImport } from './routes/api.health.recent'
import { Route as ApiHealthTodayRouteImport } from './routes/api.health.today'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitosRoute = HabitosRouteImport.update({
  id: '/habitos',
  path: '/habitos',
  getParentRoute: () => rootRouteImport,
} as any)
const HojeRoute = HojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => rootRouteImport,
} as any)
const MesRoute = MesRouteImport.update({
  id: '/mes',
  path: '/mes',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjetivosRoute = ObjetivosRouteImport.update({
  id: '/objetivos',
  path: '/objetivos',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisIndexRoute = MaisIndexRouteImport.update({
  id: '/mais/',
  path: '/mais/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosProjectIdRoute = ProjetosProjectIdRouteImport.update({
  id: '/projetos/$projectId',
  path: '/projetos/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthDebugRoute = ApiHealthDebugRouteImport.update({
  id: '/api/health/debug',
  path: '/api/health/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRecentRoute = ApiHealthRecentRouteImport.update({
  id: '/api/health/recent',
  path: '/api/health/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthTodayRoute = ApiHealthTodayRouteImport.update({
  id: '/api/health/today',
  path: '/api/health/today',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/habitos': typeof HabitosRoute
  '/hoje': typeof HojeRoute
  '/mes': typeof MesRoute
  '/objetivos': typeof ObjetivosRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/mais/': typeof MaisIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/api/health/debug': typeof ApiHealthDebugRoute
  '/api/health/recent': typeof ApiHealthRecentRoute
  '/api/health/today': typeof ApiHealthTodayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/habitos': typeof HabitosRoute
  '/hoje': typeof HojeRoute
  '/mes': typeof MesRoute
  '/objetivos': typeof ObjetivosRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/mais': typeof MaisIndexRoute
  '/projetos': typeof ProjetosIndexRoute
  '/api/health/debug': typeof ApiHealthDebugRoute
  '/api/health/recent': typeof ApiHealthRecentRoute
  '/api/health/today': typeof ApiHealthTodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/habitos': typeof HabitosRoute
  '/hoje': typeof HojeRoute
  '/mes': typeof MesRoute
  '/objetivos': typeof ObjetivosRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/mais/': typeof MaisIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/api/health/debug': typeof ApiHealthDebugRoute
  '/api/health/recent': typeof ApiHealthRecentRoute
  '/api/health/today': typeof ApiHealthTodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/financeiro'
    | '/habitos'
    | '/hoje'
    | '/mes'
    | '/objetivos'
    | '/projetos/$projectId'
    | '/mais/'
    | '/projetos/'
    | '/api/health/debug'
    | '/api/health/recent'
    | '/api/health/today'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/financeiro'
    | '/habitos'
    | '/hoje'
    | '/mes'
    | '/objetivos'
    | '/projetos/$projectId'
    | '/mais'
    | '/projetos'
    | '/api/health/debug'
    | '/api/health/recent'
    | '/api/health/today'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/financeiro'
    | '/habitos'
    | '/hoje'
    | '/mes'
    | '/objetivos'
    | '/projetos/$projectId'
    | '/mais/'
    | '/projetos/'
    | '/api/health/debug'
    | '/api/health/recent'
    | '/api/health/today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FinanceiroRoute: typeof FinanceiroRoute
  HabitosRoute: typeof HabitosRoute
  HojeRoute: typeof HojeRoute
  MesRoute: typeof MesRoute
  ObjetivosRoute: typeof ObjetivosRoute
  ProjetosProjectIdRoute: typeof ProjetosProjectIdRoute
  MaisIndexRoute: typeof MaisIndexRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
  ApiHealthDebugRoute: typeof ApiHealthDebugRoute
  ApiHealthRecentRoute: typeof ApiHealthRecentRoute
  ApiHealthTodayRoute: typeof ApiHealthTodayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habitos': {
      id: '/habitos'
      path: '/habitos'
      fullPath: '/habitos'
      preLoaderRoute: typeof HabitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoje': {
      id: '/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof HojeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes': {
      id: '/mes'
      path: '/mes'
      fullPath: '/mes'
      preLoaderRoute: typeof MesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objetivos': {
      id: '/objetivos'
      path: '/objetivos'
      fullPath: '/objetivos'
      preLoaderRoute: typeof ObjetivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mais/': {
      id: '/mais/'
      path: '/mais'
      fullPath: '/mais/'
      preLoaderRoute: typeof MaisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$projectId': {
      id: '/projetos/$projectId'
      path: '/projetos/$projectId'
      fullPath: '/projetos/$projectId'
      preLoaderRoute: typeof ProjetosProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/debug': {
      id: '/api/health/debug'
      path: '/api/health/debug'
      fullPath: '/api/health/debug'
      preLoaderRoute: typeof ApiHealthDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/recent': {
      id: '/api/health/recent'
      path: '/api/health/recent'
      fullPath: '/api/health/recent'
      preLoaderRoute: typeof ApiHealthRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/today': {
      id: '/api/health/today'
      path: '/api/health/today'
      fullPath: '/api/health/today'
      preLoaderRoute: typeof ApiHealthTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FinanceiroRoute: FinanceiroRoute,
  HabitosRoute: HabitosRoute,
  HojeRoute: HojeRoute,
  MesRoute: MesRoute,
  ObjetivosRoute: ObjetivosRoute,
  ProjetosProjectIdRoute: ProjetosProjectIdRoute,
  MaisIndexRoute: MaisIndexRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
  ApiHealthDebugRoute: ApiHealthDebugRoute,
  ApiHealthRecentRoute: ApiHealthRecentRoute,
  ApiHealthTodayRoute: ApiHealthTodayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
