/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as HabitosRouteImport } from './routes/habitos'
import { Route as HojeRouteImport } from './routes/hoje'
import { Route as MesRouteImport } from './routes/mes'
import { Route as ObjetivosRouteImport } from './routes/objetivos'
import { Route as SemanaRouteImport } from './routes/semana'
import { Route as MaisIndexRouteImport } from './routes/mais.index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as ProjetosProjectIdRouteImport } from './routes/projetos.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitosRoute = HabitosRouteImport.update({
  id: '/habitos',
  path: '/habitos',
  getParentRoute: () => rootRouteImport,
} as any)
const HojeRoute = HojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => rootRouteImport,
} as any)
const MesRoute = MesRouteImport.update({
  id: '/mes',
  path: '/mes',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjetivosRoute = ObjetivosRouteImport.update({
  id: '/objetivos',
  path: '/objetivos',
  getParentRoute: () => rootRouteImport,
} as any)
const SemanaRoute = SemanaRouteImport.update({
  id: '/semana',
  path: '/semana',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisIndexRoute = MaisIndexRouteImport.update({
  id: '/mais/',
  path: '/mais/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosProjectIdRoute = ProjetosProjectIdRouteImport.update({
  id: '/projetos/$projectId',
  path: '/projetos/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/habitos': typeof HabitosRoute
  '/hoje': typeof HojeRoute
  '/mes': typeof MesRoute
  '/objetivos': typeof ObjetivosRoute
  '/semana': typeof SemanaRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/mais/': typeof MaisIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/habitos': typeof HabitosRoute
  '/hoje': typeof HojeRoute
  '/mes': typeof MesRoute
  '/objetivos': typeof ObjetivosRoute
  '/semana': typeof SemanaRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/mais': typeof MaisIndexRoute
  '/projetos': typeof ProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/habitos': typeof HabitosRoute
  '/hoje': typeof HojeRoute
  '/mes': typeof MesRoute
  '/objetivos': typeof ObjetivosRoute
  '/semana': typeof SemanaRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/mais/': typeof MaisIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/financeiro'
    | '/habitos'
    | '/hoje'
    | '/mes'
    | '/objetivos'
    | '/semana'
    | '/projetos/$projectId'
    | '/mais/'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/financeiro'
    | '/habitos'
    | '/hoje'
    | '/mes'
    | '/objetivos'
    | '/semana'
    | '/projetos/$projectId'
    | '/mais'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/financeiro'
    | '/habitos'
    | '/hoje'
    | '/mes'
    | '/objetivos'
    | '/semana'
    | '/projetos/$projectId'
    | '/mais/'
    | '/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FinanceiroRoute: typeof FinanceiroRoute
  HabitosRoute: typeof HabitosRoute
  HojeRoute: typeof HojeRoute
  MesRoute: typeof MesRoute
  ObjetivosRoute: typeof ObjetivosRoute
  SemanaRoute: typeof SemanaRoute
  ProjetosProjectIdRoute: typeof ProjetosProjectIdRoute
  MaisIndexRoute: typeof MaisIndexRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habitos': {
      id: '/habitos'
      path: '/habitos'
      fullPath: '/habitos'
      preLoaderRoute: typeof HabitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoje': {
      id: '/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof HojeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes': {
      id: '/mes'
      path: '/mes'
      fullPath: '/mes'
      preLoaderRoute: typeof MesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objetivos': {
      id: '/objetivos'
      path: '/objetivos'
      fullPath: '/objetivos'
      preLoaderRoute: typeof ObjetivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semana': {
      id: '/semana'
      path: '/semana'
      fullPath: '/semana'
      preLoaderRoute: typeof SemanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mais/': {
      id: '/mais/'
      path: '/mais'
      fullPath: '/mais/'
      preLoaderRoute: typeof MaisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$projectId': {
      id: '/projetos/$projectId'
      path: '/projetos/$projectId'
      fullPath: '/projetos/$projectId'
      preLoaderRoute: typeof ProjetosProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FinanceiroRoute: FinanceiroRoute,
  HabitosRoute: HabitosRoute,
  HojeRoute: HojeRoute,
  MesRoute: MesRoute,
  ObjetivosRoute: ObjetivosRoute,
  SemanaRoute: SemanaRoute,
  ProjetosProjectIdRoute: ProjetosProjectIdRoute,
  MaisIndexRoute: MaisIndexRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
